version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    environment:
      GRADLE_OPTS: -Xmx1024m -Dorg.gradle.daemon=false

    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Build app
          command: ./gradlew build
