version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    environment:
      GRADLE_OPTS: -Xmx1024m -Dorg.gradle.daemon=false

    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Export app env vars
          command: |
            set -e ;
            echo "export BUILD_NO=${CIRCLE_BUILD_NUM}" >> $BASH_ENV
            echo "export COMMIT_SHA1=${CIRCLE_SHA1}" >> $BASH_ENV
      - run:
          name: Build app
          command: ./gradlew build
      - run:
          name: Publish jar
          command: ./gradlew publish
